# Generated by Django 5.2 on 2025-04-29 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='formflow.bay')),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='formflow.bed')),
            ],
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amounts', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formflow.bay')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formflow.bed')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formflow.variety')),
            ],
        ),
        migrations.CreateModel(
            name='WeekEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=20)),
                ('amounts', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bay', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formflow.bay')),
                ('bed', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formflow.bed')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formflow.variety')),
            ],
        ),
    ]
